[package]
name = "platform-nintendo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raylib = { version = "= 3.5", features=["nobuild"] }
raylib-sys = {version = "= 3.5"}